### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by tedr56** [Schamper/nodebb-plugin-buzzer#1]
Hi,

with last version of NodeBB, it causes this : 

```
10 sent a buzz to 1
TypeError: Cannot read property '1' of undefined
    at Buzzer.sockets.buzz (/home/tchernobob/NodeBB/node_modules/nodebb-plugin-buzzer/library.js:23:33)
    at callMethod (/home/tchernobob/NodeBB/src/socket.io/index.js:138:12)
    at Socket.<anonymous> (/home/tchernobob/NodeBB/src/socket.io/index.js:168:5)
    at Socket.EventEmitter.emit [as $emit] (events.js:95:17)
    at SocketNamespace.handlePacket (/home/tchernobob/NodeBB/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/home/tchernobob/NodeBB/node_modules/socket.io-wildcard/index.js:11:42)
    at XHRPolling.Transport.onMessage (/home/tchernobob/NodeBB/node_modules/socket.io/lib/transport.js:387:20)
    at XHRPolling.HTTPTransport.onData (/home/tchernobob/NodeBB/node_modules/socket.io/lib/transports/http.js:99:10)
    at IncomingMessage.<anonymous> (/home/tchernobob/NodeBB/node_modules/socket.io/lib/transports/http.js:69:12)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
^[[32minfo^[[39m: [app] Restarting...
1 sent a buzz to 10
TypeError: Cannot read property '10' of undefined
    at Buzzer.sockets.buzz (/home/tchernobob/NodeBB/node_modules/nodebb-plugin-buzzer/library.js:23:33)
    at callMethod (/home/tchernobob/NodeBB/src/socket.io/index.js:138:12)
    at Socket.<anonymous> (/home/tchernobob/NodeBB/src/socket.io/index.js:168:5)
    at Socket.EventEmitter.emit [as $emit] (events.js:95:17)
    at SocketNamespace.handlePacket (/home/tchernobob/NodeBB/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/home/tchernobob/NodeBB/node_modules/socket.io-wildcard/index.js:11:42)
    at WebSocket.Transport.onMessage (/home/tchernobob/NodeBB/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/home/tchernobob/NodeBB/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)
    at Parser.EventEmitter.emit (events.js:95:17)
    at finish (/home/tchernobob/NodeBB/node_modules/socket.io/lib/transports/websocket/hybi-16.js:288:16)
```

**Comment by Schamper** [comment]
Looks like a also forgot to remove a console.log... Will look into this later!
